import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";



const Home = ({ }) => {

    return (
        <div className={styles.container}>
            <Head>
                <title>SuperDigiFundo | Funds Application Digitized</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="min-h-screen">
                <div className="flex flex-row min-w-full">
                    <div className="flex-1 flex justify-center items-enter py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24 mb-8 lg:w-1/2">
                        <div className="mx-auto w-full max-w-sm lg flex flex-col justify-center items-center ">
                            <Image src={"/logo.png"} width={320} height={65} alt="logo" />
                            <div className="mb-8 mt-6 ">
                                <h2 className="text-xl text-gray-600 text-center">
                                    Wilkommen zur bayrischen Förderungsan
                                    fragensbearbeitungs platform
                                </h2>
                            </div>

                            <div className="mt-6 w-full">
                                <form
                                    action="#"
                                    method=""
                                    className="space-y-6"
                                >
                                    <div className="space-y-1">
                                        <label
                                            htmlFor="userID"
                                            className="block text-sm font-medium text-gray-700"
                                        >
                                            Persönliche Staats ID
                                        </label>
                                        <div className="mt-1">
                                            <input
                                                id="userID"
                                                name="userID"
                                                type="text"
                                                autoComplete="user-id"
                                                className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-pink-500 focus:border-sky-500 sm:text-sm"
                                            />
                                            <label htmlFor="userID">

                                            </label>
                                        </div>
                                    </div>

                                    <div className="space-y-1">
                                        <label
                                            htmlFor="password"
                                            className="block text-sm font-medium text-gray-700"
                                        >
                                            Passwort
                                        </label>

                                        <div className="mt-1">
                                            <input
                                                id="password"
                                                name="userPassword"
                                                type="password"
                                                autoComplete="current-password"
                                                className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-pink-500 focus:border-sky-500 sm:text-sm"
                                            />
                                            <label htmlFor="password">
                                                <p className="text-pink-700 text-xs mt-1">

                                                </p>
                                            </label>
                                        </div>
                                    </div>

                                    <div className="mb-8">
                                        <Link href="/forderungsantrage" passHref>
                                            <button
                                                className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-pink-600 hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:pink-sky-500"
                                            >
                                                Anmelden
                                            </button>
                                        </Link>

                                    </div>

                                    <div className="space-y-2 text-sm mt-8">
                                        <p className="text-center">
                                            Passwort vergessen? Kein Passwort
                                            erhalten?
                                        </p>

                                        <Link href="/" passHref>
                                            <a className="w-full flex justify-center px-4 font-medium text-pink-600  hover:text-pink-400 focus:outline focus:ring-2 ">
                                                Kontaktiere IT
                                            </a>
                                        </Link>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div className="lg:bg-[url('/bg1.png')] lg:w-1/2 bg-cover min-h-screen"></div>
                </div>
            </div>
        </div>
    );
};

export default Home;
